fix #1513 Make Restart button more visible
VirtoCommerce/vc-platform pull request #1514
Opened 2019-01-28 10:33 UTC by anivirtoway

fix  #1513 Make Restart button more visible by showing modal dialog for user

2019-01-28 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=1514) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=1514) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: anivirtoway<br/>:x: Andrey Nikutin<br/><hr/>**Andrey Nikutin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-platform?pullRequest=1514) it.</sub>

2019-01-28 11:20 UTC, yecli commented
Could you also add video with the changes demonstration?

2019-01-28 11:50 UTC, niksan321 commented
![restart_dialog](https://user-images.githubusercontent.com/2101530/51834660-0c08e500-230c-11e9-8046-d03481bb6535.gif)

2019-01-28 11:56 UTC, yecli requested changes

2019-01-28 11:56 UTC, yecli commented on VirtoCommerce.Platform.Web/Localizations/ru.VirtoCommerce.Platform.json
> +          "message": "Требуется перезагрузка приложения, перегрузить сейчасц?"
Redundant "ц" in "сейчасц".

2019-01-28 12:15 UTC, yecli approved these changes

2019-01-29 11:50 UTC, yecli commented
Created under wrong account

2019-01-29 11:50 UTC, closed without merging