VP-4566: Refactor move rules to localization
VirtoCommerce/vc-platform pull request #2009
Opened 2020-09-03 10:28 UTC by Vectorfield4

This PR is a part of FIX. https://virtocommerce.atlassian.net/browse/VP-4566

### Problem
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Solution
A clear and concise description of what you want to happen.

### Proposed of changes
Describe the technical details of realization provided by you.

### Additional context (optional)
Add any other context or screenshots about the feature request here.

### Make sure these boxes are checked:
- [ ] Check all the changes in github PR - files count (non of them are redundant, have meaningful changes, all are added), if target branch is correct
- [ ] Check methods and variable namings - it should be self descriptive, no typos
- [ ] Check you did not introduce breaking changes in API and public models/services.
- [ ] Respect extensibility - https://community.virtocommerce.com/t/extensibility-basics-the-domain-model-and-persistence-layer-extension/141
- [ ] Follow [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and [SOLID](https://en.wikipedia.org/wiki/SOLID) principles
- [ ] For unit tests - follow Microsoft best practices: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices
- [ ] Consolidate solution dependencies in case you are using newer version, update VC module dependencies in module.manifest. Do not upgrade 3rd party packages that are shipped with the platform with the version newer than in the platform.
- [ ] Check code style conventions - https://github.com/VirtoCommerce/styleguide/blob/master/csharp.md
- [ ] Check PR have a concise and descriptive title, follow [git commit message rules](https://github.com/VirtoCommerce/styleguide/blob/master/gitcommits.md)

2020-09-03 10:40 UTC, AliveMen approved these changes

2020-09-03 10:46 UTC, pushnitsa requested changes

2020-09-03 10:46 UTC, pushnitsa commented on src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.js
> +        function ($scope, translate, assets, bladeNavigationService, dialogService, $storage, bladeUtils, uiGridHelper) {
please keep $ symbol

2020-09-03 10:53 UTC, pushnitsa approved these changes

2020-09-03 14:29 UTC, AliveMen approved these changes

2020-09-04 07:09 UTC, tatarincev approved these changes

2020-09-07 09:31 UTC, yecli approved these changes

2020-09-07 09:37 UTC, merged