VP-5352: Fix vulnerability in LicensingController
VirtoCommerce/vc-platform pull request #2068
Opened 2020-10-12 15:38 UTC by Vectorfield4

### Problem
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Solution
A clear and concise description of what you want to happen.

### Proposed of changes
Describe the technical details of realization provided by you.

### Additional context (optional)
Add any other context or screenshots about the feature request here.

### Make sure these boxes are checked:
- [x] Check all the changes in github PR - files count (non of them are redundant, have meaningful changes, all are added), if target branch is correct
- [x] Check methods and variable namings - it should be self descriptive, no typos
- [x] Check you did not introduce breaking changes in API and public models/services.
- [x] Respect extensibility - https://community.virtocommerce.com/t/extensibility-basics-the-domain-model-and-persistence-layer-extension/141
- [x] Follow [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and [SOLID](https://en.wikipedia.org/wiki/SOLID) principles
- [x] For unit tests - follow Microsoft best practices: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices
- [x] Consolidate solution dependencies in case you are using newer version, update VC module dependencies in module.manifest. Do not upgrade 3rd party packages that are shipped with the platform with the version newer than in the platform.
- [x] Check code style conventions - https://github.com/VirtoCommerce/styleguide/blob/master/csharp.md
- [x] Check PR have a concise and descriptive title, follow [git commit message rules](https://github.com/VirtoCommerce/styleguide/blob/master/gitcommits.md)

2020-10-13 06:51 UTC, yecli requested changes

2020-10-13 06:51 UTC, yecli commented on src/VirtoCommerce.Platform.Web/Controllers/Api/LicensingController.cs
> +                    return BadRequest(new { Error = $"License server returns {httpResponse.StatusCode} status code" });
Seems that with the addition of BadRequests, client-side license should be reworked accordingly, so the user could see a proper message, not just empty error. In fact it is breaking change in the public API behavior, you need to think and check how it behaves after that.
Please check how the new code works with:
https://github.com/VirtoCommerce/vc-platform/blob/5d51ae50fddded58be04a454db8daa65e2b94518/src/VirtoCommerce.Platform.Web/wwwroot/js/app/licensing/license-detail.js#L20

2020-10-13 14:26 UTC, yecli approved these changes

2020-10-14 07:28 UTC, tatarincev approved these changes

2020-10-14 08:12 UTC, merged