#VP-6471 fix UserChangedEvent
VirtoCommerce/vc-platform pull request #2128
Opened 2021-01-13 19:30 UTC by kostyrin

there was ref of exists user
and security handlers are called twice 
https://virtocommerce.atlassian.net/browse/VP-6471

2021-01-14 07:35 UTC, yecli requested changes
I thought the main purpose of this task is to have NewEnity properly updated (after save) in the `UserChangedEvent`.
Now seems `UserChangedEvent` still gets the same `ApplicationUser` model as before, which was built before the changes. So imho this was not done.
Something similar was done for orders: https://github.com/VirtoCommerce/vc-module-order/blob/dev/src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs#L181
There are fixes for other problems (better to describe them carefully in the PR title - problem, reason, fix), but looks like it is not related to VP-6471 main problem.

2021-01-14 08:04 UTC, kostyrin commented
> I thought the main purpose of this task is to have NewEnity properly updated (after save) in the `UserChangedEvent`.
> Now seems `UserChangedEvent` still gets the same `ApplicationUser` model as before, which was built before the changes (but when saving some user properties could be updated). So imho this was not done.
> Something similar was done for orders: https://github.com/VirtoCommerce/vc-module-order/blob/dev/src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs#L181
> There are fixes for other problems (better to describe them carefully in the PR title - problem, reason, fix), but looks like it is not related to VP-6471 main problem.
have added more details in the description

2021-01-15 13:01 UTC, kostyrin commented
have talked with Ivan Tselishchev and get info that need to get only difference between NewEntry and OldEntry (according to the method https://github.com/VirtoCommerce/vc-platform/blob/251759cc769d9f89e03e74d6d97b61795cd0a693/src/VirtoCommerce.Platform.Security/Handlers/LogChangesUserChangedEventHandler.cs#L62). There are no a spacial cases like in the Order Module.

2021-01-15 13:04 UTC, yecli approved these changes

2021-01-15 13:29 UTC, yecli approved these changes

2021-01-18 09:09 UTC, OlegoO approved these changes

2021-01-18 09:11 UTC, merged