Configuration of password expiration policy
VirtoCommerce/vc-platform pull request #2193
Opened 2021-03-26 09:16 UTC by eMazeika

https://virtocommerce.atlassian.net/browse/PT-81

2021-03-26 09:25 UTC, mvktsk commented
Review task https://virtocommerce.atlassian.net/browse/VP-7333 has been created

2021-03-26 09:25 UTC, akak1977 approved these changes

2021-03-26 11:37 UTC, Vectorfield4 approved these changes

2021-03-29 08:07 UTC, ksavosteev approved these changes

2021-03-29 08:09 UTC, tatarincev requested changes
Also we need a write unit-tests for this logic

2021-03-29 08:09 UTC, tatarincev commented on src/VirtoCommerce.Platform.Core/Security/UserOptionsExtended.cs
> +        public TimeSpan MaxPasswordAge { get; set; }
Please make TimeSpan nullable if you decided to ignore my recommendation to name this setting as MaxPasswordAgeInDays

2021-03-29 08:09 UTC, tatarincev commented on src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs
> +                var lastPasswordChangeDate = user.LastPasswordChangedDate ?? user.CreatedDate;
Please move the code for evaluation the PasswordExpired to this place, and do not call update for user.
https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/Security/CustomUserManager.cs#L287

2021-03-29 19:52 UTC, Vectorfield4 approved these changes

2021-03-30 06:58 UTC, tatarincev approved these changes

2021-03-30 07:42 UTC, merged