PT-209: vc-build improvements
VirtoCommerce/vc-platform pull request #2215
Opened 2021-04-16 11:48 UTC by krankenbro

### Added
- Targets: Init, Install, InstallPlatform, InstallModules,, Uninstall

2021-04-19 06:04 UTC, akak1977 approved these changes

2021-04-19 08:24 UTC, Vectorfield4 requested changes

2021-04-19 08:24 UTC, Vectorfield4 commented on build/PlatformTools/GithubManager.cs
> +        public static Tuple<string, string> GetRepoFromUrl(string url)
Add XML doc what does first and the second parameter means.
``` csharp
/// <summary>
/// Do something
/// </summary>
```

2021-04-19 08:24 UTC, Vectorfield4 commented on build/PlatformTools/GithubManager.cs
> +            return release;
```suggestion
            return string.IsNullOrEmpty(releaseTag)
                ? await client.Repository.Release.GetLatest(GithubUser, moduleRepo)
                : await client.Repository.Release.Get(GithubUser, moduleRepo, releaseTag);
```

2021-04-19 08:24 UTC, Vectorfield4 commented on build/PlatformTools/LocalModuleCatalog.cs
> +            _catalog.Reload();
Any reason to Load/Reload operation sequentially?

2021-04-19 08:25 UTC, akak1977 commented on build/PlatformTools/Build.PackageManager.cs
> +        var platformWeb = RootDirectory / "VirtoCommerce.Platform.Web.dll";
No need I think. It's normal way for NUKE.

2021-04-19 08:25 UTC, akak1977 commented on build/PlatformTools/Build.PackageManager.cs
> +        var platformZip = TemporaryDirectory / "platform.zip";
No need I think. It's normal way for NUKE.

2021-04-19 08:30 UTC, Vectorfield4 commented on build/PlatformTools/Build.PackageManager.cs
> +        var platformZip = TemporaryDirectory / "platform.zip";
Yes, I forgot about `/` operator. Thanks.

2021-04-19 08:30 UTC, Vectorfield4 commented on build/PlatformTools/Build.PackageManager.cs
> +        var platformWeb = RootDirectory / "VirtoCommerce.Platform.Web.dll";
Yes, I forgot about `/` operator. Thanks.

2021-04-19 23:25 UTC, Vectorfield4 approved these changes

2021-04-20 09:47 UTC, tatarincev approved these changes

2021-04-20 12:57 UTC, merged