vc-build 1.7.2
VirtoCommerce/vc-platform pull request #2253
Opened 2021-05-07 10:52 UTC by krankenbro

2021-05-07 10:55 UTC, mvktsk commented
Review task https://virtocommerce.atlassian.net/browse/VP-7391 has been created

2021-05-18 10:58 UTC, Vectorfield4 requested changes

2021-05-18 10:58 UTC, Vectorfield4 commented on build/Build.cs
> +            var errors = processEnd.Output.Where(o => !o.Text.Contains(@"The 'files' list in config file 'tsconfig.json' is empty") && o.Type == OutputType.Err);
Prevent double enumeration.
```suggestion
            var errors = processEnd.Output.Where(o => !o.Text.Contains(@"The 'files' list in config file 'tsconfig.json' is empty") && o.Type == OutputType.Err).ToList();
```

2021-05-18 10:58 UTC, Vectorfield4 commented on build/PlatformTools/AppSettingsExtension.cs
>              return result;
```suggestion
            return result ?? defaultDiscoveryPath ;
```

2021-05-18 10:58 UTC, Vectorfield4 commented on build/PlatformTools/Build.PackageManager.cs
> +        return result;
`result` is always false.

2021-05-18 10:58 UTC, Vectorfield4 commented on build/PlatformTools/GithubManager.cs
> +                client.Credentials = new Credentials(token);
```suggestion
                Client.Credentials = new Credentials(token);
```

2021-05-18 10:58 UTC, Vectorfield4 commented on build/PlatformTools/PackageManager.cs
> +        public static PackageManifest CreatePackageManifest(string platformVersion)
```suggestion
        public static PackageManifest BuildDefaultPackageManifest(string platformVersion)
```

2021-05-18 13:47 UTC, merged