PT-1765: Validation Assets
VirtoCommerce/vc-platform pull request #2270
Opened 2021-05-25 15:58 UTC by ErickLipin

https://virtocommerce.atlassian.net/browse/PT-1764

2021-05-25 15:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=2270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=2270) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-platform?pullRequest=2270) it.</sub>

2021-05-25 18:10 UTC, akak1977 commented on src/VirtoCommerce.Platform.Web/Controllers/Api/AssetsController.cs
> +                return BadRequest("Please, specify all deleting assets urls.");
I think it's better to say:
"Please, specify at least one asset URL to delete."

2021-05-26 08:57 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs
> +                    continue;
```suggestion
            foreach (var url in urls.Where(x => !string.IsNullOrWhiteSpace(x)))
            {
```

2021-05-26 09:13 UTC, Vectorfield4 requested changes
Sign CLA

2021-05-26 18:07 UTC, Vectorfield4 requested changes

2021-05-26 18:07 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs
> +                    continue;
Redundant check. Remove it.

2021-05-28 10:32 UTC, merged