Fix add analytics in docs
VirtoCommerce/vc-platform pull request #2329
Opened 2021-07-14 15:05 UTC by blazemachine

(fix)
remove deprecated yml config section
add google-tag-manager + google-analytics

https://rush-agency.monday.com/boards/1328347443/pulses/1352240984

2021-07-14 15:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=2329) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=2329) before we can accept your contribution.<br/>**16** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: tatarincev<br/>:white_check_mark: kostyrin<br/>:white_check_mark: yecli<br/>:white_check_mark: blazemachine<br/>:white_check_mark: Woland2k<br/>:white_check_mark: trueboroda<br/>:white_check_mark: ilyawzrd<br/>:white_check_mark: AliveMen<br/>:white_check_mark: anivirtoway<br/>:white_check_mark: akak1977<br/>:white_check_mark: tpitlik<br/>:white_check_mark: lnetrebskii<br/>:white_check_mark: t13ka<br/>:white_check_mark: pushnitsa<br/>:white_check_mark: mvktsk<br/>:white_check_mark: OlegoO<br/>:x: AkulovOleg<br/>:x: OlegO<br/><hr/>**OlegO** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-platform?pullRequest=2329) it.</sub>

2021-07-14 15:11 UTC, mvktsk commented
Review task https://virtocommerce.atlassian.net/browse/VP-7562 has been created

2021-07-14 15:57 UTC, vkrashenko requested changes
Change file name from head-include to scripts-loader

2021-07-16 08:17 UTC, blazemachine commented
Closed. #60b5fe0 exists in https://github.com/VirtoCommerce/vc-platform/pull/2331 and already merged.

2021-07-16 08:18 UTC, closed without merging