PT-50: Update Generic Crud SearchService
VirtoCommerce/vc-platform pull request #2349
Opened 2021-08-20 12:20 UTC by aizhuli

## Description
Update generic crud search service by including post-read processing of search results since additional processing logic is required by implementations  in modules

## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-2261
### Artifact URL:

2021-08-20 14:08 UTC, akak1977 approved these changes

2021-08-23 17:08 UTC, akak1977 requested changes

2021-08-23 17:08 UTC, akak1977 commented on src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
> +        protected virtual Task AfterDeleteAsync(IEnumerable<TModel> models, IEnumerable<GenericChangedEntry<TModel>> changedEntries)
Does it really need?
Why not just override _Delete_, then call _base.Delete_ inside of, then do your custom actions.

2021-08-24 04:22 UTC, aizhuli commented on src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
> +        protected virtual Task AfterDeleteAsync(IEnumerable<TModel> models, IEnumerable<GenericChangedEntry<TModel>> changedEntries)
If entry changed events need to be published only after all necessary actions are done, we need this method.

2021-08-24 05:49 UTC, akak1977 commented on src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
> +        protected virtual Task AfterDeleteAsync(IEnumerable<TModel> models, IEnumerable<GenericChangedEntry<TModel>> changedEntries)
Ок

2021-08-24 17:36 UTC, akak1977 approved these changes

2021-08-31 09:18 UTC, mvktsk commented
Actual PR https://github.com/VirtoCommerce/vc-platform/pull/2363

2021-08-31 09:18 UTC, closed without merging