PT-8074: Modules healthcheck
VirtoCommerce/vc-platform pull request #2521
Opened 2022-06-30 07:39 UTC by getmansky

## Description
Modules and cache healthcheck
## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-8074
https://virtocommerce.atlassian.net/browse/PT-8080
### Artifact URL:

2022-06-30 11:59 UTC, ksavosteev approved these changes

2022-07-01 09:58 UTC, Vectorfield4 requested changes

2022-07-01 09:58 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/CacheHealthChecker.cs
> +                return Task.FromResult(HealthCheckResult.Degraded("Cache is off"));
Use unhealthy.

2022-07-01 09:58 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/ModulesHealthChecker.cs
> +                return Task.FromResult(HealthCheckResult.Degraded("Some modules have errors", null, errorsDictionary));
Please, add label for `null`.

2022-07-01 09:58 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/ModulesHealthChecker.cs
> +                .ToArray();
Use `ToDictionary()` here. No reason to sequence serialization.

2022-07-01 09:58 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/CacheHealthChecker.cs
> +    public class CacheHealthChecker : IHealthCheck
add `sealed`

2022-07-01 09:58 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/ModulesHealthChecker.cs
> +    public class ModulesHealthChecker : IHealthCheck
add `sealed`

2022-07-01 09:58 UTC, Vectorfield4 commented on src/VirtoCommerce.Platform.Web/Startup.cs
> +                    failureStatus: HealthStatus.Degraded,
```suggestion
                    failureStatus: HealthStatus.Unhealthy,
```

2022-07-08 06:31 UTC, merged