Change base logger to Serilog
VirtoCommerce/vc-platform pull request #2624
Opened 2023-03-03 16:08 UTC by AkulovOleg

## Description
We need to have possibilities for using different log providers. In our case we need Grafana.Loki.
So it's better to have **Serilog** for adding in partners' projects any providers which they need.

1) I didn't test the platform with ApplicationInsights, so please test it.
2) After using this library when can just add the needed Sink package to any of our custom modules and set up sink in appsettings.json file.

Description of the library: https://github.com/serilog/serilog
Here you can find available providers: https://github.com/serilog/serilog/wiki/Provided-Sinks

2023-03-03 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=2624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-platform?pullRequest=2624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-platform?pullRequest=2624) it.</sub>

2023-03-03 16:09 UTC, AkulovOleg commented on src/VirtoCommerce.Platform.Web/Program.cs
> -                  logging.AddEventSourceLogger();
Do you still need logging of event sources?

2023-03-24 13:48 UTC, ksavosteev requested changes

2023-03-24 13:48 UTC, ksavosteev commented on src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
> +        <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
Add `<PackageReference Include="Serilog.Extensions.Hosting" Version="5.0.1" />`.

2023-03-27 09:46 UTC, AkulovOleg commented on src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
> +        <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
added

2023-03-27 09:57 UTC, AkulovOleg commented on src/VirtoCommerce.Platform.Web/Program.cs
> +              .UseSerilog((context, loggerConfiguration) =>
changed

2023-03-27 09:57 UTC, AkulovOleg commented on src/VirtoCommerce.Platform.Web/appsettings.Development.json
> +      "Default": "Trace",
changed

2023-04-24 13:54 UTC, OlegoO commented
Replaced with 
https://github.com/VirtoCommerce/vc-platform/pull/2644
https://github.com/VirtoCommerce/vc-module-app-insights

2023-04-24 13:54 UTC, closed without merging