PT-13884: Dynamic dictionary item name must be required.
VirtoCommerce/vc-platform pull request #2715
Opened 2023-10-24 07:03 UTC by OlegoO

## Description
fix: Dynamic dictionary item name must be required. DynamicPropertyDictionaryItem without name (null or empty) will be skipped on Save.

## References
### QA-test:
### Jira-link:
### Artifact URL:

2023-10-24 09:14 UTC, ksavosteev requested changes

2023-10-24 09:14 UTC, ksavosteev commented on src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs
> +                BadRequest(ex.Message);
return missed

2023-10-24 09:18 UTC, artem-dudarev commented on src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs
> +            }
There is no need to catch different types of exception if we always return BadRequest(ex.Message)

2023-10-25 12:33 UTC, ksavosteev approved these changes

2023-10-25 12:36 UTC, artem-dudarev approved these changes

2023-10-30 08:22 UTC, merged